name: Keep Reddit Social Issues Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Allows manual triggering
  push:  # Remove this after testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Reddit Social Issues App
        run: |
          curl -f -s https://reddit-social-issues.streamlit.app/ || echo "App might be sleeping, that's okay"
          echo "Pinged Reddit Social Issues app at $(date)"
